# Generated by Django 3.0.5 on 2022-01-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='photo',
        ),
    ]
