name: hireme
description: HireMe
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.1.7
  font_awesome_flutter: ^8.8.1
  fluttertoast: ^7.0.0
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.4.2
  fl_chart: ^0.12.3
  http: ^0.12.0
  flutter_svg: ^0.19.0
  image_picker: ^0.6.6+5
  image_cropper: ^1.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/photos/
  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/fredoka.ttf
          weight: 600
